### ISSUE TITLE
@blechadler help is misleading

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/Blechadler#21]
multiple commands dont require a `help` in front of the actual command - as is falsely listed under `blechadler help`

examples:
`@blechadler help channels`  -- > `@blechadler channels`
`@blechadler help about` -- > `@blechadler about`

**Comment by DerZade** [comment]
The `@blechadler help` is meant as an overview of all command-helps. The listed commands are not meant as an example for the commands but more like a explanation on how to access the help of that specific command. 
Basically You could configure the Blechadler-help to show the help of the command `reminder add` when the user types `@blechadler help Erinnerungen setzen`.

I think this should be clear to the user when he notices that all commands are listet with a leading `help` or at least when the user is prompted with the help for command xy when typing `@blechadler help xy`, which then includes explanation, syntax and most importantly examples.

**Comment by DerZade** [comment]
Fixed in 51161fd, f919884 and 5956530
